### ISSUE TITLE
GAnalyzer for Kubuntu asking for QT version 5.13

### ISSUE THREAD

**Issue by lexterror** [QTinman/GAnalyzer#1]
Hi, I have Kubuntu 19.10 installed and Kubuntu 19.10 comes with QT version 5.12.

GAnalyzer is asking for QT version 5.13

It won't let me run your program.

Thank you!

**Comment by QTinman** [comment]
Hi, so did you download binaries or compile from source?

Also do you have any errormessages you can show me?

Let me know if you solved the problem.

Regards.

**Comment by lexterror** [comment]
I downloaded the binaries from this site.

Kubuntu 19.10 comes with QT 5.12 not 5.13

https://i.imgur.com/eVz4Cj8.png

**Comment by QTinman** [comment]
Can you try the v0.2 just to see if that will run, my Qt was upgraded to 5.13 some days ago and 0.2.1 binaries are probably from that build. 
I guess you need to update Qt or your dependencies.

**Comment by lexterror** [comment]
I already tried :)

**Comment by QTinman** [comment]
Or eventually recompile from source.
Btw same error from old version?

**Comment by lexterror** [comment]
Yes, same error.

**Comment by QTinman** [comment]
Can you compile from source?

**Comment by lexterror** [comment]
Is it a set of commands or do I need to use an IDE to compile?

**Comment by QTinman** [comment]
Or I will use some old laptops laying around to install kubuntu and compile on that.
Like I say in comments, binaries are compiled on ubuntu 16.04

**Comment by lexterror** [comment]
The QT version on Ubuntu 16.04 must be even older..

**Comment by lexterror** [comment]
If you get it to compile I'll definitely try it out. Thanks for your help!

**Comment by QTinman** [comment]
Can I post picture here?

**Comment by lexterror** [comment]
Ok

**Comment by QTinman** [comment]
![QT ubuntu 16 04](https://user-images.githubusercontent.com/56702508/68630546-fbff7200-04e7-11ea-8a59-7d7305aebc8c.png)

**Comment by QTinman** [comment]
you need qt creator

**Comment by lexterror** [comment]
Ok, Thanks!

**Comment by QTinman** [comment]
Good luck :)
