### ISSUE TITLE
Desperate need of help and have new way of obtaining answers from the numbers to share with anyone interested.

### ISSUE THREAD

**Issue by sizzlean1973** [QTinman/GAnalyzer#2]
Wow this place is daunting to say the least.  I originally came here for some help that is probably such a joke for everyone here but I can't seem to figure out how to get it done. I have been using gematrinator and I only use three numbers..english, sumerian, and jewish and wonder if it is possible to somehow make it so that when I click on a number that instead of it showing me the number properties in that seperate box like it does I would like to have it link to it's number in two directories in which I have the Greek and Hebrew Lexicons saved locally on my hard drive thereby pulling them up or it would be even better if I could get it to grab certain lines like the definitions and put them in a pretty little window and/or save that as a file?  I hope that makes sense and that I did not bother you with a stupid question.  If you can help me I'd sure appreciate it as the way I'm doing it is so time and resource consuming on this junker pc I have.  
   Now on the same topic I would love to show you the way I do it and I'm about a 99% sure you've never seen it done this way and it would probably blow your mind to see what I'd like to show you.  My email is monkeysizzlean@gmail.com if you would like to hit me up so we could chat, if not I totally understand.  I'm not a programmer and feel like a kindergardner pretending to fit in with the 9th graders and any moment someone is going to spot me and lecture me in front of the whole school.  Peace

**Comment by QTinman** [comment]
Hi, as you say you would like to point to your local drive, that should be doable if your lexicons are searchable  with that number clicked.
As I see it would be relative easy by using offline version of Gematrinator and reprogram the part witch open up the number properties to point to your local lexicons.

**Comment by sizzlean1973** [comment]
So I'll check it out and see if I can figure or find something.  It sure
would be nice if I could talk to you on the phone once I gather all the pix
showing what I'm after and hopefully find something I can understand in the
file but if it's an exe I can use total commander to view or edit it but if
it's machine language I don't know nothing about that.  I appreciate your
reply and this would be soooo cool and a huge help to me.  I'm going to put
a link to a really cool gematria presentation about the architects of
deception,  aka the (should I give it away?)  no ,  you'll find it
interesting I promise, mainly how it is used.
Here you go:  enjoy:  https://youtu.be/esvCL3840a0    and I'll let you know
what I find when I do, maybe after a nap.  Thanks so much
